import { useMemo, useState } from "react";
import { ArrowRight, Camera, CheckCircle2, ClipboardList, MapPin, Search, SlidersHorizontal, UserRound } from "lucide-react";
import "./_group.css";
import { DemoNote, PropertyCard, PropertyIcon, PropertyType, WareefBrand, saveRequest, serviceData } from "./_shared";

type View="home"|"services"|"form"|"summary"|"orders";
const copy={ar:{home:"الرئيسية",services:"الخدمات",orders:"طلباتي",account:"حسابي",title:"مساحتك الخضراء تستحق عناية تُرى",sub:"خدمات للحدائق المنزلية والمزارع، من مختصين قريبين منك.",browse:"تصفح الخدمات",matching:"مختصون يناسبون طلبك",request:"طلب خدمة",quote:"اطلب عرض سعر",submit:"إرسال الطلب التجريبي",back:"رجوع",size:"المساحة التقريبية",work:"العمل المطلوب",photos:"صور للمكان",location:"الموقع",date:"التاريخ المفضل",garden:"اسم الحديقة (اختياري)",crops:"الأشجار أو المحاصيل (اختياري)",details:"تفاصيل إضافية (اختياري)",farmArea:"مساحة الأرض",summary:"ملخص طلبك",sent:"تم حفظ طلب بانتظار تحديد السعر",empty:"لا يوجد مختصون مطابقون في هذا الموقع الآن.",try:"جرّب موقعاً آخر أو وسّع نطاق البحث.",homeGarden:"حديقة منزلية",farm:"مزرعة",city:"الرياض · العليا",past:"اختر تاريخ اليوم أو تاريخاً مستقبلياً.",upfront:"التسعير"},en:{home:"Home",services:"Services",orders:"My requests",account:"Account",title:"Care for every growing space",sub:"Trusted specialists for home gardens and farms near you.",browse:"Browse services",matching:"Specialists for your request",request:"Book service",quote:"Request a quote",submit:"Submit demo request",back:"Back",size:"Approximate size",work:"Requested work",photos:"Space photos",location:"Location",date:"Preferred date",garden:"Garden name (optional)",crops:"Trees or crops (optional)",details:"Additional details (optional)",farmArea:"Land area",summary:"Your request summary",sent:"Your pricing-pending demo request is saved",empty:"No matching specialists are available here.",try:"Try a different location or broaden the search.",homeGarden:"Home garden",farm:"Farm",city:"Riyadh · Olaya",past:"Choose today or a future date.",upfront:"Pricing"}};

export function Customer(){
 const [view,setView]=useState<View>("home"),[english,setEnglish]=useState(false),[property,setProperty]=useState<PropertyType>("home"),[service,setService]=useState("maintenance"),[location,setLocation]=useState("Olaya"),[dateError,setDateError]=useState(false);
 const [form,setForm]=useState({size:"",garden:"",crops:"",details:"",date:""});
 const t=english?copy.en:copy.ar, dir=english?"ltr":"rtl", today=new Date().toISOString().slice(0,10), selected=serviceData.find(s=>s.id===service)!;
 const matches=useMemo(()=>location.toLowerCase()!=="remote",[location]);
 const selectProperty=(p:PropertyType)=>{setProperty(p);setView("services")};
 const submit=()=>{if(!form.date||form.date<today){setDateError(true);return}saveRequest({id:Date.now().toString(),property,service,location,date:form.date,size:form.size,garden:form.garden,crops:form.crops,details:form.details,quote:true,created:new Date().toLocaleDateString()});setView("summary")};
 const serviceName=(s:typeof serviceData[number])=>english?(property==="farm"?s.enFarm:s.enHome):(property==="farm"?s.farm:s.home);
 return <div className="ghars" dir={dir}><div className="shell">
 {view==="home"&&<><header className="hero"><div className="top"><WareefBrand/><button className="lang" onClick={()=>setEnglish(!english)}>{english?"عربي":"EN"}</button></div><h1>{t.title}</h1><p className="muted">{t.sub}</p></header><section className="section"><div className="section-head"><h2>{english?"Choose your property":"اختر نوع المساحة"}</h2><span className="small">{english?"Two ways to grow":"خدمتان لمساحتك"}</span></div><div className="property-grid"><PropertyCard type="home" onClick={()=>selectProperty("home")} english={english}/><PropertyCard type="farm" onClick={()=>selectProperty("farm")} english={english}/></div></section><section className="section"><div className="section-head"><h2>{t.matching}</h2><button className="outline" onClick={()=>setView("services")}>{t.browse}</button></div><div className="card provider"><div className="avatar">م</div><div style={{flex:1}}><b>{english?"Mazen Garden Care":"حدائق مازن"}</b><p className="small"><MapPin size={10}/> {t.city} · 4.9</p><div className="support"><span>{t.homeGarden}</span><span>{t.farm}</span></div></div><ArrowRight size={16} color="#1F5C43"/></div></section></>}
  {view==="services"&&<><header className="form-head"><div className="top"><button className="back" onClick={()=>setView("home")}>← {t.back}</button><button className="lang" onClick={()=>setEnglish(!english)}>{english?"عربي":"EN"}</button></div><h1>{english?"Find the right service":"اعثر على الخدمة المناسبة"}</h1></header><section className="section"><div className="filters"><select value={property} onChange={e=>setProperty(e.target.value as PropertyType)}><option value="home">{t.homeGarden}</option><option value="farm">{t.farm}</option></select><select value={service} onChange={e=>setService(e.target.value)}>{serviceData.map(s=><option key={s.id} value={s.id}>{serviceName(s)}</option>)}</select><input className="filterwide" value={location} onChange={e=>setLocation(e.target.value)} placeholder={t.location}/></div><div className="section-head"><h2>{t.matching}</h2><SlidersHorizontal size={15}/></div>{matches?<><div className="card provider"><div className="avatar">م</div><div style={{flex:1}}><b>{english?"Mazen Garden Care":"حدائق مازن"}</b><p className="small"><MapPin size={10}/> {location} · 3.1 km</p><div className="support"><span>{t.homeGarden}</span><span>{t.farm}</span></div></div></div><div className="service-list" style={{marginTop:10}}>{serviceData.map(s=><div className="service" key={s.id}><button onClick={()=>{setService(s.id);setView("form")}}><b>{serviceName(s)}</b><span>{english?"To be determined later":"تُحدّد لاحقاً"}</span></button></div>)}</div></>:<div className="card empty"><Search size={24}/><h2>{t.empty}</h2><p>{t.try}</p></div>}</section></>}
  {view==="form"&&<><header className="form-head"><button className="back" onClick={()=>setView("services")}>← {t.back}</button><h1>{property==="farm"?t.quote:t.request}</h1><p>{property==="farm"?(english?"Tell the specialist about your land.":"عرّف المختص على أرضك واحتياجك."):(english?"A few details help your gardener arrive ready.":"تفاصيل بسيطة تجعل المختص مستعداً عند الوصول.")}</p></header><main className="form-card"><div className="pill"><PropertyIcon type={property} size={14}/> {property==="farm"?t.farm:t.homeGarden}</div><label>{t.work}</label><select value={service} onChange={e=>setService(e.target.value)}>{serviceData.map(s=><option key={s.id} value={s.id}>{serviceName(s)}</option>)}</select>{property==="home"&&<><label>{t.garden}</label><input value={form.garden} onChange={e=>setForm({...form,garden:e.target.value})}/></>}<label>{property==="farm"?t.farmArea:t.size}</label><div className="row"><input value={form.size} onChange={e=>setForm({...form,size:e.target.value})} placeholder={english?"e.g. 120":"مثال: ١٢٠"}/><select style={{width:110}}><option>{property==="farm"?(english?"hectares":"هكتار"):(english?"m²":"م²")}</option><option>{property==="farm"?(english?"m²":"م²"):(english?"ft²":"قدم²")}</option></select></div>{property==="farm"&&<><label>{t.crops}</label><input value={form.crops} onChange={e=>setForm({...form,crops:e.target.value})}/></>}<label>{t.details}</label><textarea value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/><label>{t.photos}</label><div className="upload"><Camera size={18}/><br/>{english?"Add up to 5 photos":"أضف حتى ٥ صور"}</div><label>{t.location}</label><input value={location} onChange={e=>setLocation(e.target.value)}/><label>{t.date}</label><input type="date" min={today} value={form.date} onChange={e=>{setDateError(false);setForm({...form,date:e.target.value})}}/>{dateError&&<p className="small" style={{color:"#a45032"}}>{t.past}</p>}<div className="notice" style={{margin:"12px 0"}}>{t.upfront}: {english?"To be determined later":"تُحدّد لاحقاً"}</div><button className="cta" onClick={submit}>{t.submit}</button></main></>}
  {view==="summary"&&<main className="section" style={{paddingTop:46}}><div className="card" style={{textAlign:"center"}}><CheckCircle2 color="#1F5C43" size={40}/><h1 style={{fontSize:21}}>{t.sent}</h1><p className="muted">{english?"It now appears in Mazen’s local demo dashboard.":"يظهر الآن في لوحة مازن التجريبية المحلية."}</p></div><div className="quote-card" style={{marginTop:12}}><h2>{t.summary}</h2><p>{property==="farm"?t.farm:t.homeGarden} · {serviceName(selected)}</p>{property==="home"&&form.garden&&<p className="small">{t.garden.replace(/ \(.*\)/,"")}: {form.garden}</p>}<p className="small">{location} · {form.size||"—"} · {form.date}</p><p><b>{t.upfront}: {english?"To be determined later":"تُحدّد لاحقاً"}</b></p></div><DemoNote english={english}/><button className="cta" onClick={()=>setView("orders")}>{t.orders}</button></main>}
 {view==="orders"&&<section className="section"><h2>{t.orders}</h2><div className="card" style={{marginTop:12}}><b>{property==="farm"?t.quote:t.request}</b><p className="small">{property==="farm"?t.farm:t.homeGarden} · {location}</p><span className="tag">{english?"Awaiting provider":"بانتظار المختص"}</span></div></section>}
 <DemoNote english={english}/><div className="bottom"><button className={`nav ${view==="home"?"active":""}`} onClick={()=>setView("home")}><PropertyIcon type="home"/>{t.home}</button><button className={`nav ${view==="services"?"active":""}`} onClick={()=>setView("services")}><Search/>{t.services}</button><button className={`nav ${view==="orders"?"active":""}`} onClick={()=>setView("orders")}><ClipboardList/>{t.orders}</button><button className="nav"><UserRound/>{t.account}</button></div>
 </div></div>
}