import { useEffect, useState } from "react";
import { CalendarDays, ClipboardList, MapPin, Save, UserRound } from "lucide-react";
import "./_group.css";
import { DemoNote, DemoRequest, getRequests, PropertyIcon, serviceData, WareefBrand } from "./_shared";

const x={ar:{studio:"مساحة المختص",title:"طلبات تحتاج ردك",requests:"الطلبات",calendar:"المواعيد",profile:"الملف والخدمات",profileTitle:"حدائق مازن",saved:"تم الحفظ محلياً",save:"حفظ الملف",support:"أنواع المساحات المدعومة",both:"الحدائق المنزلية والمزارع",quote:"إرسال عرض تجريبي بانتظار التسعير",offered:"تم إرسال العرض التجريبي بانتظار التسعير",empty:"لا توجد طلبات تجريبية جديدة بعد.",garden:"الحديقة",price:"التسعير"},en:{studio:"Provider studio",title:"Requests waiting for you",requests:"Requests",calendar:"Schedule",profile:"Profile & services",profileTitle:"Mazen Garden Care",saved:"Saved locally",save:"Save profile",support:"Supported property types",both:"Home gardens & farms",quote:"Send pricing-pending demo proposal",offered:"Pricing-pending demo proposal sent",empty:"No new demo requests yet.",garden:"Garden",price:"Pricing"}};
export function Provider(){
 const [tab,setTab]=useState("requests"),[english,setEnglish]=useState(false),[requests,setRequests]=useState<DemoRequest[]>(getRequests()),[supported,setSupported]=useState({home:true,farm:true}),[saved,setSaved]=useState(false),[offered,setOffered]=useState("");
 const t=english?x.en:x.ar;
 useEffect(()=>{const sync=()=>setRequests(getRequests());window.addEventListener("storage",sync);window.addEventListener("wareef-demo-update",sync);return()=>{window.removeEventListener("storage",sync);window.removeEventListener("wareef-demo-update",sync)}},[]);
 return <div className="ghars" dir={english?"ltr":"rtl"}><div className="shell"><header className="hero"><div className="top"><WareefBrand/><button className="lang" onClick={()=>setEnglish(!english)}>{english?"عربي":"EN"}</button></div><span className="pill">{t.studio}</span><h1>{t.title}</h1></header><div className="statgrid"><div className="stat"><b>{requests.length+2}</b><span>{t.requests}</span></div><div className="stat"><b>4.9</b><span>{english?"Rating":"التقييم"}</span></div><div className="stat"><b>2</b><span>{english?"Today":"اليوم"}</span></div></div><div className="tabs"><button className={tab==="requests"?"on":""} onClick={()=>setTab("requests")}>{t.requests}</button><button className={tab==="calendar"?"on":""} onClick={()=>setTab("calendar")}>{t.calendar}</button><button className={tab==="profile"?"on":""} onClick={()=>setTab("profile")}>{t.profile}</button></div>
 {tab==="requests"&&<main className="screen">{requests.map(r=><article className="request" key={r.id}><div className="row"><div><b>{r.property==="farm"?(english?"Farm quote request":"طلب عرض سعر لمزرعة"):(english?"Home garden request":"طلب حديقة منزلية")}</b><p className="small"><MapPin size={10}/> {r.location} · {r.date}</p></div><span className="tag">{english?"New":"جديد"}</span></div><div className="mini"><span><PropertyIcon type={r.property} size={11}/> {r.property==="farm"?(english?"Farm":"مزرعة"):(english?"Home garden":"حديقة منزلية")}</span><span>{r.size||"—"} {r.property==="farm"?(english?"hectares":"هكتار"):(english?"m²":"م²")}</span></div>{r.garden&&<p className="small">{t.garden}: {r.garden}</p>}<p className="small">{r.details||r.crops||"—"}</p><p className="small"><b>{t.price}: {english?"To be determined later":"تُحدّد لاحقاً"}</b></p><button className="cta" style={{marginTop:9}} onClick={()=>setOffered(r.id)}>{offered===r.id?t.offered:t.quote}</button></article>)}{requests.length===0&&<div className="card empty"><ClipboardList size={25}/><p>{t.empty}</p></div>}<article className="request"><b>{english?"Neda House Garden":"حديقة بيت الندى"}</b><p className="small">{english?"Al Olaya · regular maintenance · To be determined later":"العليا · صيانة دورية · تُحدّد لاحقاً"}</p></article></main>}
 {tab==="calendar"&&<main className="screen"><div className="quote-card"><b>{english?"Al Salem home maintenance":"صيانة منزل السالم"}</b><p className="small">{english?"Today · 4:00 PM":"اليوم · ٤:٠٠ م"}</p></div></main>}
 {tab==="profile"&&<main className="screen"><div className="form-card"><h2>{t.profileTitle}</h2><label>{t.support}</label><div className="row"><button className={`outline ${supported.home?"on":""}`} onClick={()=>setSupported({...supported,home:!supported.home})}>{english?"Home gardens":"الحدائق المنزلية"} {supported.home?"✓":""}</button><button className="outline" onClick={()=>setSupported({...supported,farm:!supported.farm})}>{english?"Farms":"المزارع"} {supported.farm?"✓":""}</button></div><p className="small" style={{marginTop:7}}>{t.both}</p><label>{english?"Coverage":"نطاق التغطية"}</label><input defaultValue={english?"Olaya, Al Wurud, Hittin":"العليا، الورود، حطين"}/><label>{english?"Shared published services":"الخدمات المشتركة المنشورة"}</label>{serviceData.slice(0,3).map(s=><div className="service" key={s.id}><button><b>{english?s.enHome:s.home}</b><span>{english?"To be determined later":"تُحدّد لاحقاً"}</span></button></div>)}<button className="cta" style={{marginTop:13}} onClick={()=>setSaved(true)}><Save size={14}/> {saved?t.saved:t.save}</button></div></main>}
 <DemoNote english={english}/><div className="bottom"><button className="nav active" onClick={()=>setTab("requests")}><ClipboardList/>{t.requests}</button><button className="nav" onClick={()=>setTab("calendar")}><CalendarDays/>{t.calendar}</button><button className="nav" onClick={()=>setTab("profile")}><UserRound/>{t.profile}</button></div></div></div>
}