// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ghars/Admin.tsx": () => import("../components/mockups/ghars/Admin.tsx"),
  "./components/mockups/ghars/Customer.tsx": () => import("../components/mockups/ghars/Customer.tsx"),
  "./components/mockups/ghars/Provider.tsx": () => import("../components/mockups/ghars/Provider.tsx"),
  "./components/mockups/wareef-hub/Current.tsx": () => import("../components/mockups/wareef-hub/Current.tsx"),
  "./components/mockups/wareef-hub/Refined.tsx": () => import("../components/mockups/wareef-hub/Refined.tsx"),
  "./components/mockups/wareef-previous/Admin.tsx": () => import("../components/mockups/wareef-previous/Admin.tsx"),
  "./components/mockups/wareef-previous/Customer.tsx": () => import("../components/mockups/wareef-previous/Customer.tsx"),
  "./components/mockups/wareef-previous/ProductShowcase.tsx": () => import("../components/mockups/wareef-previous/ProductShowcase.tsx"),
  "./components/mockups/wareef-previous/Provider.tsx": () => import("../components/mockups/wareef-previous/Provider.tsx"),
  "./components/mockups/wareef-previous/ProviderOnboarding.tsx": () => import("../components/mockups/wareef-previous/ProviderOnboarding.tsx"),
  "./components/mockups/wareef-previous/ProviderReviewConsole.tsx": () => import("../components/mockups/wareef-previous/ProviderReviewConsole.tsx")
};
