import { ChangeEvent, useRef, useState } from "react";
import { Camera, Flower2, ImagePlus, LoaderCircle, Save, Send, Sparkles, Upload } from "lucide-react";
import { Plant, designProviders, plants } from "./_DesignData";

export type DesignPreferences={city:string;dimensions:string;sun:"full"|"mixed";style:string};
export type LocalDesign={id:number;title:string;photo:string;concept:string;plan:Plant[];preferences:DesignPreferences;details:string};
type Props={english:boolean;signedIn:boolean;onSignIn:()=>void;onSave:(design:LocalDesign)=>void;onQuote:(design:LocalDesign,provider:string)=>void;saved:LocalDesign[]};
export function DesignJourney({english,signedIn,onSignIn,onSave,onQuote}:Props){
 const L=english,uploadRef=useRef<HTMLInputElement>(null),cameraRef=useRef<HTMLInputElement>(null);
 const [step,setStep]=useState<"upload"|"preferences"|"loading"|"result"|"error"|"quote">("upload"),[photo,setPhoto]=useState(""),[prefs,setPrefs]=useState<DesignPreferences>({city:"Riyadh",dimensions:"",sun:"full",style:"Calm courtyard"}),[plan,setPlan]=useState<Plant[]>([]),[error,setError]=useState(""),[consent,setConsent]=useState(false),[provider,setProvider]=useState("nawa");
 const chooseFile=(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;if(!file.type.startsWith("image/")){setError(L?"Choose an image file.":"اختر ملف صورة.");return}if(photo.startsWith("blob:"))URL.revokeObjectURL(photo);setPhoto(URL.createObjectURL(file));setError("")};
 const update=(key:keyof DesignPreferences,value:string)=>setPrefs(p=>({...p,[key]:value}));
 const current=():LocalDesign=>({id:Date.now(),title:L?"Courtyard calm plan":"خطة فناء هادئ",photo,concept:"/__mockup/images/wareef-garden-sunrise.jpg",plan,preferences:prefs,details:`${prefs.city} · ${prefs.dimensions} m · ${prefs.sun} · ${prefs.style} · ${L?"Pricing to be determined later":"تُحدّد الأسعار لاحقاً"}`});
 const prepare=()=>{if(!photo){setError(L?"Add a photo of your space before continuing.":"أضف صورة لمساحتك قبل المتابعة.");setStep("upload");return}if(!prefs.city||!prefs.dimensions){setError(L?"Complete city and dimensions to prepare a plan.":"أكمل المدينة والأبعاد لإعداد الخطة.");return}if(!signedIn){onSignIn();setError(L?"Demo sign-in complete. Select Generate sample concept again.":"اكتمل الدخول التجريبي. اختر إنشاء التصور التجريبي مرة أخرى.");return}const planned=plants.filter(p=>prefs.sun==="full"?p.sun.toLowerCase().includes("full"):p.sun.toLowerCase().includes("shade")).slice(0,3);setPlan(planned.length?planned:plants.slice(0,3));setError("");setStep("loading");window.setTimeout(()=>setStep("result"),700)};
 const retry=()=>{setError("");setStep("preferences")};
 if(step==="loading")return <section className="design-screen"><div className="design-loading"><LoaderCircle/><h2>{L?"Preparing the planting plan first":"نُعد خطة الزراعة أولاً"}</h2><p>{L?"Regional suitability, sunlight and your preferences are being matched locally.":"تُطابق الملاءمة الإقليمية والشمس وتفضيلاتك محلياً."}</p></div></section>;
 if(step==="error")return <section className="design-screen"><div className="empty-state"><h2>{L?"Sample preparation paused":"توقف إعداد النموذج"}</h2><p>{error|| (L?"The local sample could not be prepared.":"تعذر إعداد النموذج المحلي.")}</p><button className="cta" onClick={retry}>{L?"Retry":"إعادة المحاولة"}</button></div></section>;
 if(step==="quote"){const d=current();return <section className="design-screen"><button className="back" onClick={()=>setStep("result")}>← {L?"Back":"رجوع"}</button><p className="eyebrow">IMPLEMENTATION · DEMO</p><h1>{L?"Request an implementation quote":"اطلب عرض سعر للتنفيذ"}</h1><p className="small">{L?"The selected provider receives this local photo, illustrative sample, plant plan and preference details only after consent.":"يستلم المختص المختار هذه الصورة المحلية والتصور التوضيحي وخطة الزراعة والتفضيلات فقط بعد الموافقة."}</p><div className="provider-pick">{designProviders.map(p=><label key={p.id}><input type="radio" name="provider" value={p.id} checked={provider===p.id} onChange={()=>setProvider(p.id)}/><b>{L?p.en:p.ar}</b><small>{p.distance} · ★ {p.rating}</small></label>)}</div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>{L?"I consent to privately share the original photo, illustrative concept, plant plan and preferences with this selected demo provider.":"أوافق على مشاركة الصورة الأصلية والتصور التوضيحي وخطة الزراعة والتفضيلات بشكل خاص مع المختص التجريبي المختار."}</label>{error&&<p className="selection-error">{error}</p>}<button className="cta" disabled={!consent} onClick={()=>{if(!signedIn){onSignIn();setError(L?"Demo sign-in complete. Submit again.":"اكتمل الدخول التجريبي. أرسل مرة أخرى.");return}onQuote(d,provider);setError("");setStep("result")}}><Send size={16}/>{L?"Submit demo request":"إرسال الطلب التجريبي"}</button></section>}
 if(step==="result"){const d=current();return <section className="design-screen"><p className="eyebrow">SAMPLE DEMONSTRATION · عرض تجريبي</p><h1>{L?"Your garden direction":"اتجاه حديقتك"}</h1><div className="sample-notice"><Sparkles size={17}/><b>{L?"AI-generated concept — sample demonstration":"تصور مبدئي بالذكاء الاصطناعي — عرض تجريبي"}</b><span>{L?"The proposed image is illustrative only: it cannot mirror this uploaded photo or guarantee the listed plants are shown. No photo analysis or feature preservation occurred.":"الصورة المقترحة توضيحية فقط: لا يمكنها محاكاة صورتك المرفوعة أو ضمان ظهور النباتات المذكورة. لم يحدث تحليل للصورة أو حفظ لمعالمها."}</span></div><div className="compare"><figure><img src={photo} alt={L?"Your locally selected original photo":"صورتك الأصلية المختارة محلياً"}/><figcaption>{L?"Original photo — private local preview":"الصورة الأصلية — معاينة محلية خاصة"}</figcaption></figure><figure><img src={d.concept} alt={L?"Illustrative garden concept sample":"نموذج تصور الحديقة التوضيحي"}/><figcaption>{L?"Illustrative concept sample":"نموذج التصور التوضيحي"}</figcaption></figure></div><h2>{L?"Planting plan":"خطة الزراعة"}</h2><p className="small">{L?"Prepared first from the regional catalogue and your preferences. A provider confirms site suitability, quantities and final pricing.":"تم إعدادها أولاً من الكتالوج الإقليمي وتفضيلاتك. يؤكد المختص ملاءمة الموقع والكميات والسعر النهائي."}</p><div className="plant-list">{plan.map(p=><article key={p.botanical}><Flower2/><div><b>{p.ar} · {p.en}</b><small><i>{p.botanical}</i></small><p>{L?`Sun: ${p.sun} · Water: ${p.water} · Care: ${p.care}`:`الشمس: ${p.sun} · الري: ${p.water} · العناية: ${p.care}`}</p></div><em>{p.region}</em></article>)}</div><div className="design-actions"><button className="outline" onClick={()=>setStep("preferences")}>{L?"Adjust design":"تعديل التصميم"}</button><button className="outline" onClick={()=>{if(!signedIn){onSignIn();setError(L?"Demo sign-in complete. Save again.":"اكتمل الدخول التجريبي. احفظ مرة أخرى.");return}onSave(d)}}><Save size={15}/>{L?"Save design":"حفظ التصميم"}</button><button className="cta" onClick={()=>{if(!signedIn){onSignIn();setError(L?"Demo sign-in complete. Request a quote again.":"اكتمل الدخول التجريبي. اطلب العرض مرة أخرى.");return}setConsent(false);setError("");setStep("quote")}}>{L?"Request quote":"اطلب عرض سعر"}</button></div>{error&&<p className="selection-error">{error}</p>}</section>}
  return <section className="design-screen"><h1>{L?"Design Your Garden":"صمّم حديقتك"}</h1>{step==="upload"?<><div className={`photo-uploader ${photo?"has-photo":""}`}>{photo&&<img src={photo} alt={L?"Local garden preview":"معاينة الحديقة المحلية"}/>}<ImagePlus/><b>{photo?(L?"Photo ready for the local plan":"الصورة جاهزة للخطة المحلية"):(L?"Upload the space":"ارفع صورة المساحة")}</b><small>{L?"Share photos of your space so we can help you design it.":"شاركنا صور مساحتك لنساعدك في تصميمها."}</small><div><button className="outline" onClick={()=>cameraRef.current?.click()}><Camera size={15}/>{L?"Take photo":"التقاط صورة"}</button><button className="outline" onClick={()=>uploadRef.current?.click()}><Upload size={15}/>{photo?(L?"Replace":"استبدال"):(L?"Choose image":"اختيار صورة")}</button></div><input ref={uploadRef} hidden type="file" accept="image/*" onChange={chooseFile}/><input ref={cameraRef} hidden type="file" accept="image/*" capture="environment" onChange={chooseFile}/></div>{error&&<p className="selection-error">{error}</p>}<button className="cta" onClick={()=>{if(!photo){setError(L?"A photo is required for this design journey.":"الصورة مطلوبة لرحلة التصميم هذه.");return}setError("");setStep("preferences")}}>{L?"Continue":"متابعة"}</button></>:<><div className="design-form"><label>{L?"City":"المدينة"}<input value={prefs.city} onChange={e=>update("city",e.target.value)}/></label><label>{L?"Approx. dimensions (m)":"الأبعاد التقريبية (م)"}<input value={prefs.dimensions} onChange={e=>update("dimensions",e.target.value)} placeholder="6 × 4" inputMode="decimal"/></label><label>{L?"Sun exposure":"التعرض للشمس"}<select value={prefs.sun} onChange={e=>update("sun",e.target.value)}><option value="full">{L?"Full sun":"شمس كاملة"}</option><option value="mixed">{L?"Mixed shade":"ظل متناوب"}</option></select></label><label>{L?"Garden style":"نمط الحديقة"}<select value={prefs.style} onChange={e=>update("style",e.target.value)}><option value="Calm courtyard">{L?"Calm courtyard":"فناء هادئ"}</option><option value="Productive garden">{L?"Productive garden":"حديقة مثمرة"}</option></select></label><p className="policy-note">{L?"Pricing to be determined later; no budget is collected in this demo.":"تُحدّد الأسعار لاحقاً؛ لا يتم جمع ميزانية في هذا العرض."}</p></div><div className="notice">{L?"Demo sign-in is required to generate, save, or submit. No real account, AI credentials, upload, storage or network request exists.":"يتطلب التوليد والحفظ والإرسال دخولاً تجريبياً. لا يوجد حساب أو بيانات ذكاء اصطناعي أو رفع أو تخزين أو طلب شبكي حقيقي."}</div>{error&&<p className="selection-error">{error}</p>}<button className="cta" onClick={prepare}><Sparkles size={16}/>{signedIn?(L?"Generate sample concept":"أنشئ تصوراً تجريبياً"):(L?"Demo sign in to continue":"دخول تجريبي للمتابعة")}</button></>}</section>
}