import { useMemo, useState } from "react";
import { AlertTriangle, BadgeCheck, Eye, LayoutDashboard, ShieldCheck, Tags } from "lucide-react";
import "./_group.css";
import { demoStore, RequestStatus, ServiceKey, statusText, useDemoState } from "./_demoStore";
import { WareefBrand } from "./_shared";
import { MaintenanceSummary } from "./_MaintenanceDetails";
import { ProviderReviewConsole } from "./ProviderReviewConsole";
 const text={ar:{market:"إدارة السوق",overview:"نظرة عامة",providers:"المختصون والكتالوج",categories:"فئات الخدمات",issues:"متابعة الطلبات",security:"الأمان والسجل",ops:"لوحة العمليات",demo:"عرض مشترك في المتصفح",head:"إشراف الطلبات والكتالوج",pro:"المختص",scope:"الخدمات الظاهرة",price:"حالة التسعير",action:"إجراء",toggle:"تبديل الظهور"},en:{market:"Marketplace admin",overview:"Overview",providers:"Providers & catalogue",categories:"Service categories",issues:"Request oversight",security:"Security & audit",ops:"Operations desk",demo:"Shared browser demo",head:"Request and catalogue oversight",pro:"Provider",scope:"Visible offerings",price:"Pricing status",action:"Action",toggle:"Toggle visibility"}};
const services:Record<ServiceKey,[string,string]>={maintenance:["تنظيف وصيانة الحديقة","Garden cleaning & maintenance"],trim:["تقليم وتشكيل","Trimming & shaping"],plant:["زراعة موسمية","Seasonal planting"],soil:["معالجة التربة وتجهيز الأرض","Soil & ground treatment"],party:["تنسيق الحفلات","Party styling"],custom:["احتياج خاص","Custom garden need"],farm:["خدمات المزارع","Farm services"]};
const statuses:RequestStatus[]=["pending","quoted","booked","ongoing","work_completed","completed","declined","cancelled"];

export function Admin(){
 const [page,setPage]=useState("overview"),[english,setEnglish]=useState(false),[filter,setFilter]=useState("all"),[openId,setOpenId]=useState<string|null>(null),[twoStep,setTwoStep]=useState(false);
 const data=useDemoState(),t=english?text.en:text.ar,dir=english?"ltr":"rtl";
 const requests=useMemo(()=>filter==="all"?data.requests:data.requests.filter(r=>r.status===filter),[data.requests,filter]);
 const openRequest=data.requests.find(r=>r.id===openId);
 const title=page==="applications"?(english?"Provider applications":"طلبات انضمام المختصين"):page==="providers"?t.providers:page==="categories"?t.categories:page==="issues"?t.issues:page==="security"?t.security:t.overview;
 return <div className="ghars admin" dir={dir}>
   <aside className="aside"><WareefBrand inverse/><div className="eyebrow">{t.market}</div>{[[LayoutDashboard,"overview",t.overview],[BadgeCheck,"applications",english?"Provider applications":"طلبات الانضمام"],[ShieldCheck,"providers",t.providers],[Tags,"categories",t.categories],[AlertTriangle,"issues",t.issues],[ShieldCheck,"security",t.security]].map(([Icon,id,label])=>{const I=Icon as typeof LayoutDashboard;return <button className={page===id?"on":""} onClick={()=>setPage(id as string)} key={id as string}><I size={15}/>{label as string}</button>})}</aside>
  <main className="main"><header className="admin-top"><div><div className="eyebrow">{t.ops}</div><h1>{title}</h1></div><div className="row"><span className="pill">{t.demo}</span><button className="lang" onClick={()=>setEnglish(!english)}>{english?"عربي":"EN"}</button></div></header>
   <div className="metric-row"><div className="metric"><small>{english?"Pending provider / quote":"بانتظار المختص / العرض"}</small><b>{data.requests.filter(r=>r.status==="pending").length}</b></div><div className="metric"><small>{english?"Pending time proposals":"اقتراحات وقت معلّقة"}</small><b>{data.requests.filter(r=>r.timeProposal?.status==="pending").length}</b></div><div className="metric"><small>{english?"Cancelled / declined":"ملغاة / اعتذر عنها"}</small><b>{data.requests.filter(r=>["cancelled","declined"].includes(r.status)).length}</b></div></div>
   {page==="overview"&&<section className="admin-card"><h2>{english?"Marketplace rhythm":"إيقاع السوق"}</h2><p className="small">{english?"Cancellation fees, cutoff, and the actual provider response deadline are deliberately unset pending shop discussions. No automatic timer runs in this prototype.":"رسوم الإلغاء ومهلته وموعد رد المختص الفعلي غير محددة عمداً بانتظار نقاش المتاجر. لا يعمل مؤقت تلقائي في هذا النموذج."}</p></section>}
    {page==="security"&&<section className="admin-card security-demo"><h2>{english?"Admin security simulation":"محاكاة أمان الإدارة"}</h2><div className="notice"><b>{twoStep?(english?"Two-step verification simulated as enabled":"تمت محاكاة تفعيل التحقق بخطوتين"):(english?"Two-step verification required":"التحقق بخطوتين مطلوب")}</b><p>{english?"This toggle does not secure an account, send an OTP, or enforce access. It demonstrates the required second-step control only; this preview has no real authentication.":"هذا التبديل لا يؤمّن حساباً ولا يرسل رمزاً ولا يفرض وصولاً. يعرض فقط شرط الخطوة الثانية؛ لا توجد مصادقة حقيقية في المعاينة."}</p><button className="outline" onClick={()=>setTwoStep(!twoStep)}>{twoStep?(english?"Simulate disabling":"محاكاة الإيقاف"):(english?"Simulate verification":"محاكاة التحقق")}</button></div><h2>{english?"Sensitive-change audit trail":"سجل تغييرات حساسة"}</h2><table><tbody>{data.audit.length?data.audit.map(a=><tr key={a.id}><td><b>{a.target}</b><br/><span className="small">{a.detail}</span></td><td>{a.action}</td><td>{new Date(a.at).toLocaleString(english?"en-SA":"ar-SA")}</td></tr>):<tr><td>{english?"No admin decisions in this browser session yet.":"لا توجد قرارات إدارية في جلسة المتصفح هذه بعد."}</td></tr>}</tbody></table></section>}
    {page==="applications"&&<ProviderReviewConsole embedded/>}
     {page==="providers"&&<section className="admin-card"><h2>{t.providers}</h2><table><thead><tr><th>{t.pro}</th><th>{t.scope}</th><th>{t.price}</th><th>{english?"Approval":"الاعتماد"}</th><th>{t.action}</th></tr></thead><tbody>{data.providers.map(p=>{const active=Object.entries(p.offerings).filter(([,o])=>o?.enabled&&o.approved);return <tr key={p.id}><td><b>{english?p.en:p.ar}</b><br/><span className="small">{p.serviceArea}</span></td><td>{active.length} {english?"visible":"ظاهرة"}</td><td>{english?"To be determined later":"تُحدّد لاحقاً"}</td><td><span className="tag">{p.approvalStatus}</span></td><td><button className="outline" disabled={p.approvalStatus!=="approved"} onClick={()=>{const first=active[0]?.[0] as ServiceKey|undefined;if(first)demoStore.patchOffering(p.id,first,{enabled:false})}}>{t.toggle}</button></td></tr>})}</tbody></table></section>}
   {page==="categories"&&<section className="admin-card"><h2>{english?"Service catalogue":"كتالوج الخدمات"}</h2><table><tbody>{(Object.keys(services) as ServiceKey[]).map(key=><tr key={key}><td><b>{services[key][english?1:0]}</b></td><td>{data.providers.filter(p=>p.offerings[key]?.enabled).length} {english?"providers":"مختصاً"}</td><td><span className="tag">{english?"Shared catalogue":"كتالوج مشترك"}</span></td></tr>)}</tbody></table></section>}
   {page==="issues"&&<section className="admin-card"><div className="section-head"><h2>{t.head}</h2><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{english?"All statuses":"كل الحالات"}</option>{statuses.map(s=><option value={s} key={s}>{statusText(s,english)}</option>)}</select></div>
    <div className="notice admin-policy"><b>{english?"Response deadline policy awaiting shop discussions":"سياسة مهلة الرد بانتظار نقاش المتاجر"}</b><p>{english?"The demo control below is clearly a manual admin simulation, not a production timer or an invented timeout.":"أداة العرض أدناه محاكاة إدارية يدوية بوضوح، وليست مؤقت إنتاج أو مهلة مخترعة."}</p></div>
     <table><tbody>{requests.map(r=><tr key={r.id}><td><b>{r.title}</b><br/><span className="small">{r.timeProposal?.status==="pending"?(english?"Pending time proposal":"اقتراح وقت معلّق"):r.seeded?(english?"Earlier prototype":"نموذج سابق"):(english?"Shared demo":"عرض مشترك")}</span></td><td>{english?"To be determined later":"تُحدّد لاحقاً"}</td><td><span className={`tag status-${["cancelled","declined"].includes(r.status)?"error":r.status==="pending"?"pending":"approved"}`}>{statusText(r.status,english,r.quoteOnly)}</span></td><td><button className="outline" onClick={()=>setOpenId(openId===r.id?null:r.id)}><Eye size={12}/>{english?"Details":"التفاصيل"}</button></td></tr>)}</tbody></table>
     {openRequest&&<section className="admin-request-detail"><div className="row"><h2>{english?"Request detail":"تفاصيل الطلب"}</h2><button className="link" onClick={()=>setOpenId(null)}>{english?"Close":"إغلاق"}</button></div><p><b>{english?"Provider":"المختص"}:</b> {data.providers.find(p=>p.id===openRequest.providerId)?.[english?"en":"ar"]||openRequest.providerId}</p><p><b>{english?"Frozen scope":"النطاق المثبّت"}:</b> {(openRequest.scopeSnapshot?.map(s=>english?s.en:s.ar)??openRequest.services.map(s=>services[s][english?1:0])).join(" · ")}</p><p><b>{english?"Pricing":"التسعير"}:</b> {english?"To be determined later":"تُحدّد لاحقاً"}</p><p><b>{english?"Status":"الحالة"}:</b> {statusText(openRequest.status,english,openRequest.quoteOnly)}</p>
     {openRequest.preferredTime&&<p><b>{english?"Current appointment":"الموعد الحالي"}:</b> {new Date(openRequest.preferredTime).toLocaleString(english?"en-SA":"ar-SA")}</p>}
     {openRequest.timeProposal&&<div className="proposal-box"><b>{openRequest.timeProposal.status==="pending"?(english?"Time proposal pending":"اقتراح الوقت معلّق"):openRequest.timeProposal.status==="accepted"?(english?"New time accepted":"تم قبول الوقت الجديد"):(english?"Time proposal rejected":"رُفض اقتراح الوقت")}</b><span>{new Date(openRequest.timeProposal.proposedTime).toLocaleString(english?"en-SA":"ar-SA")} · {openRequest.timeProposal.proposedBy==="customer"?(english?"Customer proposal":"اقتراح العميل"):(english?"Provider proposal":"اقتراح المختص")}</span><small>{openRequest.timeProposal.status==="pending"?(english?"Original appointment remains until explicit acceptance.":"يبقى الموعد الأصلي حتى القبول الصريح."):openRequest.timeProposal.status==="accepted"?(english?"This is now the current confirmed appointment time.":"أصبح هذا هو وقت الموعد الحالي المؤكد."):(english?"The previous confirmed appointment remains unchanged.":"يبقى الموعد المؤكد السابق دون تغيير.")}</small></div>}
     {openRequest.status==="pending"&&<button className="outline admin-simulation" disabled={Boolean(openRequest.adminNoResponseDemo)} onClick={()=>demoStore.simulateNoResponse(openRequest.id)}>{openRequest.adminNoResponseDemo?(english?"Demo no-response simulated — alternatives offered":"تمت محاكاة عدم الرد — عُرضت البدائل"):(english?"Admin demo only: simulate no response":"عرض إداري فقط: محاكاة عدم الرد")}</button>}
     {openRequest.adminNoResponseDemo&&<p className="policy-note">{english?"Manual demo event only. Actual deadline remains unset. Customer is offered alternatives; provider and price are never switched automatically.":"حدث عرض يدوي فقط. المهلة الفعلية غير محددة. تُعرض بدائل للعميل ولا يتم تبديل المختص أو السعر تلقائياً."}</p>}
     {(openRequest.cancellation||openRequest.decline)&&<div className="proposal-box"><b>{english?"Cancellation / decline record":"سجل الإلغاء / الاعتذار"}</b><span>{openRequest.cancellation?.reason||openRequest.decline?.reason||(english?"No reason provided":"لم يذكر سبب")}</span><small>{english?"No payment collected; no refund needed or simulated.":"لم يتم تحصيل دفعة؛ لا يلزم استرداد ولم تتم محاكاته."}</small></div>}
     {openRequest.attachment?.maintenance&&<MaintenanceSummary english={english} value={openRequest.attachment.maintenance}/>}
    </section>}
    {!requests.length&&<div className="demo-empty">{english?"No requests match this filter.":"لا توجد طلبات مطابقة للتصفية."}</div>}
   </section>}
  </main>
 </div>;
}