import { useEffect, useMemo, useState } from "react";
import { BadgeCheck, Building2, Check, ChevronLeft, CircleAlert, FileText, MapPin, Scissors, Search, ShieldAlert, ShieldCheck, Sprout, Store, X } from "lucide-react";
import "./ProviderReviewConsole.css";
import { ApplicationStatus, demoStore, ServiceKey, useDemoState } from "./_demoStore";

const services:Record<ServiceKey,{ar:string;en:string;Icon:typeof Scissors}>={
 trim:{ar:"تقليم وتشكيل",en:"Trimming & shaping",Icon:Scissors},maintenance:{ar:"تنظيف وصيانة الحديقة",en:"Garden cleaning & maintenance",Icon:Sprout},
 plant:{ar:"زراعة موسمية",en:"Seasonal planting",Icon:Store},soil:{ar:"معالجة التربة",en:"Soil treatment",Icon:Sprout},party:{ar:"تنسيق الحفلات",en:"Party styling",Icon:Store},
 custom:{ar:"احتياج خاص",en:"Custom need",Icon:Store},farm:{ar:"خدمات المزارع",en:"Farm services",Icon:Sprout}
};
export function ProviderReviewConsole({embedded=false}:{embedded?:boolean}){
 const data=useDemoState();
 const [english,setEnglish]=useState(false),[selectedId,setSelectedId]=useState<string>(),[filter,setFilter]=useState<ApplicationStatus|"all">("pending"),[query,setQuery]=useState(""),[reason,setReason]=useState(""),[approved,setApproved]=useState<ServiceKey[]>([]);
 const t=(ar:string,en:string)=>english?en:ar,dir=english?"ltr":"rtl";
 const filtered=useMemo(()=>data.applications.filter(a=>(filter==="all"||a.status===filter)&&a.businessName.toLowerCase().includes(query.trim().toLowerCase())),[data.applications,filter,query]);
 const selected=data.applications.find(a=>a.id===selectedId)??filtered[0]??data.applications[0];
 useEffect(()=>{if(selected){setSelectedId(selected.id);setApproved(selected.approvedServices);setReason(selected.reason??"")}},[selected?.id,selected?.updatedAt]);
 const counts=(status:ApplicationStatus)=>data.applications.filter(a=>a.status===status).length;
 const statusText=(status:ApplicationStatus)=>({pending:t("بانتظار المراجعة","Pending review"),"changes-needed":t("بحاجة لتعديل","Needs changes"),rejected:t("مرفوض","Rejected"),approved:t("معتمد","Approved"),suspended:t("موقوف","Suspended")}[status]);
 const decide=(status:ApplicationStatus)=>{if(!selected)return;if(demoStore.reviewApplication(selected.id,status,approved,reason))setReason("")};
 const invite=()=>demoStore.createInvitation();
 return <div className={`provider-review ${embedded?"embedded":""}`} dir={dir}>
  {!embedded&&<aside className="review-sidebar"><div className="review-brand"><span>WAREEF</span><i>/</i><b>وريف</b></div><p>{t("إدارة المختصين","Provider operations")}</p><nav><button className="side-active"><ShieldCheck/>{t("طلبات الانضمام","Applications")}<small>{counts("pending")}</small></button><button><BadgeCheck/>{t("المختصون المعتمدون","Approved providers")}</button><button><ShieldAlert/>{t("الموقوفون","Suspended")}</button></nav><div className="review-policy"><CircleAlert/><span><b>{t("قاعدة الظهور","Visibility rule")}</b>{t("لا يظهر إلا المختص والخدمات المعتمدة والمفعلة.","Only approved providers and approved enabled services appear.")}</span></div></aside>}
  <main className="review-main"><header className="review-top"><div><span>{t("مراجعة الانضمام · محاكاة محلية","ONBOARDING REVIEW · LOCAL SIMULATION")}</span><h1>{t("طلبات المختصين","Provider applications")}</h1></div><button className="language" onClick={()=>setEnglish(!english)}>{english?"عربي":"EN"}</button></header>
   <div className="review-stats"><article><span>{t("بانتظار المراجعة","Pending")}</span><b>{counts("pending")}</b></article><article><span>{t("بحاجة لتعديل","Needs changes")}</span><b>{counts("changes-needed")}</b></article><article><span>{t("المعتمدون","Approved")}</span><b>{counts("approved")}</b></article></div>
   <section className="admin-card invitation-panel"><div><h2>{t("دعوات الإطلاق","Launch invitations")}</h2><p className="small">{t("رموز محاكاة داخل جلسة المتصفح وليست مصادقة أو حماية حقيقية.","Browser-session simulation codes, not real authentication or security.")}</p></div><button className="approve" onClick={invite}>{t("إنشاء دعوة تجريبية","Create demo invitation")}</button>{data.invitations.map(i=><code key={i.id}>{i.code} · {i.usedByApplicationId?t("مستخدمة","used"):t("متاحة","available")}</code>)}</section>
   <section className="review-workspace"><div className="application-list"><div className="list-heading"><div><h2>{t("قائمة الطلبات","Application list")}</h2><span>{t("طلبات حقيقية من نموذج الانضمام المحلي","Live browser-local submissions")}</span></div><Search/></div><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("ابحث باسم النشاط","Search business")}/></label><div className="filters">{(["pending","changes-needed","rejected","approved","suspended","all"] as const).map(id=><button key={id} className={filter===id?"selected":""} onClick={()=>setFilter(id)}>{id==="all"?t("الكل","All"):statusText(id)}</button>)}</div><div className="application-scroll">{filtered.map(a=><button className={`application-card ${selected?.id===a.id?"selected":""}`} key={a.id} onClick={()=>setSelectedId(a.id)}><span className="app-monogram">{a.businessName.slice(0,1)}</span><span><b>{a.businessName}</b><small><MapPin/>{a.serviceArea}</small><small>{new Date(a.submittedAt).toLocaleString(english?"en-SA":"ar-SA")}</small></span><i className={`status ${a.status==="changes-needed"?"changes":a.status}`}>{statusText(a.status)}</i></button>)}{!filtered.length&&<div className="no-results"><Search/><b>{t("لا توجد طلبات مطابقة","No matching applications")}</b></div>}</div></div>
    <section className="application-detail" aria-live="polite">{selected?<><div className="detail-title"><div><span className="detail-kicker">{t("طلب انضمام","Provider application")}</span><h2>{selected.businessName}</h2><p><MapPin/>{selected.serviceArea}</p></div></div><div className="detail-status"><span className={`status ${selected.status==="changes-needed"?"changes":selected.status}`}>{statusText(selected.status)}</span><p>{selected.reason||t("لا موافقة ذاتية: القرار للمشرف فقط. التعليق مطلوب للتعديل والرفض والإيقاف.","No self-approval: admin decides. A reason is required for changes, rejection, and suspension.")}</p></div>
     <div className="detail-block"><h3><Building2/>{t("بيانات النشاط","Business details")}</h3><dl><div><dt>{t("اسم النشاط","Business")}</dt><dd>{selected.businessName}</dd></div><div><dt>{t("التواصل","Contact")}</dt><dd>{selected.contact}</dd></div><div><dt>{t("منطقة الخدمة","Service area")}</dt><dd>{selected.serviceArea}</dd></div><div><dt>{t("موافقة الشروط","Terms consent")}</dt><dd>{selected.termsAccepted?t("نعم","Yes"):t("لا","No")}</dd></div></dl></div>
     <div className="detail-block"><h3><Check/>{t("الخدمات المطلوبة","Requested services")}</h3><p className="block-note">{t("اختر الاعتماد من الخدمات المطلوبة فقط. تبدأ بلا سعر ثابت (عرض سعر) حتى يضبطها المختص.","Approve only from the requested set. New offerings start unpriced/quote-only until configured.")}</p><div className="service-review">{selected.requestedServices.map(key=>{const service=services[key],Icon=service.Icon,on=approved.includes(key);return <button key={key} className={on?"approved-service":""} onClick={()=>setApproved(current=>on?current.filter(s=>s!==key):[...current,key])}><span><Icon/></span><b>{t(service.ar,service.en)}</b><i>{on?<Check/>:<X/>}</i></button>})}</div></div>
     <div className="detail-block"><h3><FileText/>{t("مستندات المراجعة","Review documents")}</h3><div className="documents">{selected.documents.map(d=>d.url?<a href={d.url} target="_blank" rel="noreferrer" key={d.name}><FileText/>{d.name}</a>:<span key={d.name}><FileText/>{d.name}</span>)}</div><p className="block-note">{t("معاينات الجلسة محلية ومؤقتة وليست تخزيناً آمناً.","Session previews are local and temporary, not secure storage.")}</p></div>
     <div className="changes-box"><label>{t("سبب القرار عند التعديل أو الرفض أو الإيقاف","Reason for changes, rejection, or suspension")}<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label></div>
     <footer className="detail-actions">{selected.status==="approved"?<button className="danger" disabled={!reason.trim()} onClick={()=>decide("suspended")}><ShieldAlert/>{t("إيقاف الظهور","Suspend")}</button>:<><button className="outline" disabled={!reason.trim()} onClick={()=>decide("changes-needed")}>{t("طلب تعديل","Request changes")}</button><button className="danger" disabled={!reason.trim()} onClick={()=>decide("rejected")}>{t("رفض","Reject")}</button><button className="approve" disabled={!approved.length} onClick={()=>decide("approved")}><BadgeCheck/>{selected.status==="suspended"?t("إعادة الاعتماد","Reapprove"):t("اعتماد المختص","Approve")}</button></>}</footer>
    </>:<div className="no-results"><ShieldCheck/><b>{t("أنشئ دعوة ثم أرسل طلباً من شاشة الانضمام.","Create an invitation, then submit from onboarding.")}</b></div>}</section>
   </section>
  </main>
 </div>
}