import { useEffect, useState } from "react";
import { BadgeCheck, Check, ChevronLeft, CircleAlert, FileText, MapPin, Scissors, ShieldCheck, Sprout, Store, Upload, UserRound } from "lucide-react";
import "./ProviderOnboarding.css";
import { ApplicationDocument, demoStore, ProviderApplication, ServiceKey, useDemoState } from "./_demoStore";

type Step = 1 | 2 | 3 | 4;
const services: Partial<Record<ServiceKey, { ar:string; en:string; noteAr:string; noteEn:string; icon:typeof Scissors }>> = {
  trim:{ar:"تقليم وتشكيل",en:"Trimming & shaping",noteAr:"العناية بالنباتات والشجيرات",noteEn:"Plant and shrub care",icon:Scissors},
  maintenance:{ar:"تنظيف وصيانة الحديقة",en:"Garden cleaning & maintenance",noteAr:"تنظيف، أعشاب، وقص العشب",noteEn:"Cleaning, weeds and mowing",icon:Sprout},
  plant:{ar:"زراعة موسمية",en:"Seasonal planting",noteAr:"زراعة وتجديد المساحات",noteEn:"Planting and garden renewal",icon:Store},
  soil:{ar:"معالجة التربة",en:"Soil treatment",noteAr:"تجهيز الأرض والتربة",noteEn:"Ground and soil preparation",icon:Sprout},
  party:{ar:"تنسيق الحفلات",en:"Party styling",noteAr:"تنسيق المساحات للمناسبات",noteEn:"Outdoor occasion styling",icon:Store},
  custom:{ar:"احتياج حديقة خاص",en:"Custom garden need",noteAr:"يتطلب معاينة وعرضاً",noteEn:"Assessment and quote required",icon:Store},
  farm:{ar:"خدمات المزارع",en:"Farm services",noteAr:"أعمال المزارع بالمعاينة",noteEn:"Assessment-based farm work",icon:Sprout}
};
const statusCopy=(app:ProviderApplication,english:boolean)=>({
  pending:english?"Pending Wareef review":"بانتظار مراجعة وريف",
  "changes-needed":english?"Changes requested":"مطلوب تعديل الطلب",
  rejected:english?"Application rejected":"تم رفض الطلب",
  approved:english?"Approved — profile activated":"معتمد — تم تفعيل الملف",
  suspended:english?"Profile suspended":"تم إيقاف الملف"
}[app.status]);

export function ProviderOnboarding(){
  const data=useDemoState();
  const [english,setEnglish]=useState(false),[step,setStep]=useState<Step>(1),[invitation,setInvitation]=useState(""),[name,setName]=useState(""),[phone,setPhone]=useState(""),[area,setArea]=useState("الرياض"),[selected,setSelected]=useState<ServiceKey[]>(["trim"]),[documents,setDocuments]=useState<ApplicationDocument[]>([]),[terms,setTerms]=useState(false),[applicationId,setApplicationId]=useState<string>(),[editing,setEditing]=useState(false),[error,setError]=useState("");
  const app=data.applications.find(a=>a.id===applicationId);
  const t=(ar:string,en:string)=>english?en:ar,dir=english?"ltr":"rtl";
  useEffect(()=>{if(!app||app.status!=="changes-needed"&&app.status!=="rejected")return;const savedInvitation=data.invitations.find(item=>item.id===app.invitationId);if(savedInvitation)setInvitation(savedInvitation.code);setName(app.businessName);setPhone(app.contact);setArea(app.serviceArea);setSelected(app.requestedServices);setDocuments(app.documents);setTerms(app.termsAccepted)},[app?.id,app?.status]);
  const invitationValid=Boolean(demoStore.invitationForCode(invitation));
  const valid=step===1?invitationValid&&name.trim().length>2&&phone.trim().length>=8:step===2?selected.length>0&&area.trim().length>1:step===3?documents.length>0:terms;
  const toggle=(service:ServiceKey)=>setSelected(current=>current.includes(service)?current.filter(item=>item!==service):[...current,service]);
  const edit=()=>{if(!app||!["changes-needed","rejected"].includes(app.status))return;const savedInvitation=data.invitations.find(item=>item.id===app.invitationId);if(savedInvitation)setInvitation(savedInvitation.code);setName(app.businessName);setPhone(app.contact);setArea(app.serviceArea);setSelected(app.requestedServices);setDocuments(app.documents);setTerms(app.termsAccepted);setStep(1);setError("");setEditing(true)};
  const cancelEdit=()=>{setEditing(false);setStep(1);setError("")};
  const submit=()=>{const result=demoStore.submitApplication({applicationId,invitationCode:invitation,businessName:name.trim(),contact:phone.trim(),serviceArea:area.trim(),requestedServices:selected,documents,termsAccepted:terms});if(result.ok){setApplicationId(result.application.id);setEditing(false);setStep(1);setError("")}else setError(t("تعذر الإرسال. تحقق من الدعوة وحالة الطلب.","Could not submit. Check the invitation and application status."))};

  if(app&&!editing)return <div className="provider-onboard" dir={dir}><main className="onboard-shell"><header className="onboard-top"><div className="wordmark">WAREEF <i>/</i> <b>وريف</b></div><button onClick={()=>setEnglish(!english)}>{english?"عربي":"EN"}</button></header><section className="submitted"><span><BadgeCheck /></span><p>{statusCopy(app,english)}</p><h1>{app.status==="approved"?t("أصبحت الخدمات التي وافق عليها المشرف متاحة للعملاء.","Admin-approved services are now available to customers."):t("طلب الانضمام مرتبط بهذه الدعوة وتتم مراجعته إدارياً.","This invitation-linked application is handled through admin review.")}</h1><div className="review-list"><div><Check/><span><b>{app.businessName}</b><small>{app.serviceArea}</small></span></div><div><ShieldCheck/><span><b>{t("حالة الطلب","Application status")}</b><small>{statusCopy(app,english)}</small></span></div>{app.reason&&<div><CircleAlert/><span><b>{t("ملاحظة المراجع","Reviewer reason")}</b><small>{app.reason}</small></span></div>}</div><div className="plain-notice"><CircleAlert/>{t("هذا نموذج محلي مشترك داخل المتصفح، وليس حساباً أو موافقة أمنية حقيقية. الملفات مؤقتة لهذه الجلسة فقط.","Shared browser-local simulation only — not real authentication or security approval. Files are temporary for this session only.")}</div>{(app.status==="changes-needed"||app.status==="rejected")&&<button className="primary" onClick={edit}>{t("تعديل الطلب وإعادة إرساله","Edit and resubmit")}</button>}</section></main></div>;

  return <div className="provider-onboard" dir={dir}><main className="onboard-shell"><header className="onboard-top"><div className="wordmark">WAREEF <i>/</i> <b>وريف</b></div><button onClick={()=>setEnglish(!english)}>{english?"عربي":"EN"}</button></header><div className="onboard-intro"><p>{t("إطلاق بالدعوات فقط · محاكاة","INVITATION-ONLY LAUNCH · SIMULATION")}</p><h1>{t("ابدأ تقديم خدماتك عبر وريف","Start offering your services on Wareef")}</h1><span>{t("يلزم رمز دعوة صالح أنشأه المشرف في هذا المتصفح.","A valid invitation created by the admin in this browser is required.")}</span></div><div className="stepper">{[1,2,3,4].map(number=><span className={number===step?"current":number<step?"done":""} key={number}>{number<step?<Check/>:number}</span>)}</div>
    <section className="form-card">
      {step===1&&<><div className="section-heading"><span><UserRound/></span><div><h2>{t("الدعوة وبيانات النشاط","Invitation & business details")}</h2><p>{t("الرمز محاكاة للعرض وليس حماية أمنية.","The code is a demo simulation, not a security control.")}</p></div></div><label>{t("رمز الدعوة","Invitation code")}<input value={invitation} onChange={e=>{setInvitation(e.target.value.toUpperCase());setError("")}} placeholder="WRF-XXXXXX"/><small>{invitation&&(invitationValid?t("دعوة صالحة","Valid invitation"):t("الدعوة غير موجودة أو لم تصل بعد","Invitation not found yet"))}</small></label><label>{t("اسم النشاط أو المختص","Business or provider name")}<input value={name} onChange={e=>setName(e.target.value)}/></label><label>{t("رقم الجوال","Mobile number")}<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel"/></label></>}
      {step===2&&<><div className="section-heading"><span><MapPin/></span><div><h2>{t("الخدمات ومنطقة العمل","Services & coverage")}</h2><p>{t("اختر فقط ما تستطيع تنفيذه.","Select only services you can deliver.")}</p></div></div><label>{t("المدينة أو منطقة الخدمة","City or service area")}<input value={area} onChange={e=>setArea(e.target.value)}/></label><fieldset><legend>{t("الخدمات المطلوبة للمراجعة","Services for review")}</legend>{(Object.keys(services) as ServiceKey[]).map(key=>{const service=services[key]!,Icon=service.icon;return <button type="button" className={`service-choice ${selected.includes(key)?"selected":""}`} onClick={()=>toggle(key)} key={key}><Icon/><span><b>{t(service.ar,service.en)}</b><small>{t(service.noteAr,service.noteEn)}</small></span><i>{selected.includes(key)&&<Check/>}</i></button>})}</fieldset></>}
      {step===3&&<><div className="section-heading"><span><FileText/></span><div><h2>{t("مستندات المراجعة","Review documents")}</h2><p>{t("لا توجد هويات حقيقية مزروعة في العرض.","No real identity documents are seeded in this demo.")}</p></div></div><label className="upload"><Upload/><span><b>{t("اختر ملفات من جهازك","Choose files from your device")}</b><small>{t("يراها مالك المتجر ومراجعو الإدارة فقط، ولا تظهر للعملاء أو المختصين الآخرين. الأسماء والمعاينة محلية لهذه الجلسة فقط وليست تخزيناً آمناً.","Visible only to this shop owner and admin reviewers, never customers or other providers. Names and previews are session-local, not secure storage.")}</small></span><input type="file" multiple onChange={e=>setDocuments(Array.from(e.target.files||[]).map(file=>({name:file.name,url:URL.createObjectURL(file)})))}/></label>{documents.map(document=><div className="file" key={document.name}><FileText/>{document.url?<a href={document.url} target="_blank" rel="noreferrer">{document.name}</a>:document.name}<Check/></div>)}</>}
      {step===4&&<><div className="section-heading"><span><Store/></span><div><h2>{t("راجع الطلب والشروط","Review & operating terms")}</h2><p>{t("لا تصبح الخدمات ظاهرة قبل موافقة المشرف لكل خدمة.","Services remain hidden until each is admin-approved.")}</p></div></div><dl className="review"><div><dt>{t("النشاط","Business")}</dt><dd>{name}</dd></div><div><dt>{t("التواصل","Contact")}</dt><dd>{phone}</dd></div><div><dt>{t("منطقة العمل","Service area")}</dt><dd>{area}</dd></div><div><dt>{t("الخدمات","Services")}</dt><dd>{selected.map(key=>t(services[key]!.ar,services[key]!.en)).join(" · ")}</dd></div></dl><label><span><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/> {t("أوافق على شروط التشغيل التجريبية: متجر بمالك واحد فقط، بلا دعوات فريق أو حسابات موظفين، ومراجعة لكل خدمة وعدم استقبال حجوزات قبل الاعتماد.","I consent to demo operating terms: one shop owner only, no team invites or staff accounts, per-service review, and no bookings before approval.")}</span></label><div className="plain-notice"><CircleAlert/>{t("تُحدّد الأسعار لاحقاً؛ لا يتم إدخال أو نشر أي سعر في هذا العرض.","Pricing is to be determined later; no price is entered or published in this demo.")}</div></>}
      {error&&<div className="plain-notice"><CircleAlert/>{error}</div>}
      <div className="form-actions">{editing&&step===1&&<button className="secondary" onClick={cancelEdit}>{t("إلغاء التعديل","Cancel edit")}</button>}{step>1&&<button className="secondary" onClick={()=>setStep(value=>Math.max(1,value-1) as Step)}><ChevronLeft/>{t("السابق","Back")}</button>}{step<4?<button className="primary" disabled={!valid} onClick={()=>valid&&setStep(value=>Math.min(4,value+1) as Step)}>{t("متابعة","Continue")}</button>:<button className="primary" disabled={!valid} onClick={submit}>{t("إرسال / إعادة إرسال الطلب","Submit / resubmit")}</button>}</div>
    </section>
  </main></div>
}